### ISSUE TITLE
rotations

### ISSUE THREAD

**Issue by Lidocian** [ike3/mangosbot-zero#8]
Hi Ike3!

Im trying to rework dps rotations. im firstly trying ret paladin(dps??  1.12 LOL) ( im not know c++ or any programing language but just  using my mind):
i cant achieve the rotation (1.12)?: target->seal of the crusader->judgement->seal of command->melee......->(judgement (on cd /8s/)->seal of command) repeat +  *consecration rank 1    / * bonus at bossfights

sry about linking text but im new on git and cant use it and im not know english well
  https://github.com/Lidocian/mangoz--ikerotations-/commit/763f05203cb1352c53cea674c218f48bf5d91f73
triggers and etc. are created  seal of the crusader and judgement  are working fine  but i dont know how i can setup it to reach  my goal.

 i hope,  with your help i can slowly undersdtand and rework the rotations ,priorities.

ps: i made a little addon for control your bots. its not a big deal ( i never created any addon and not know LUA before) but feel free to look it , and i hope you can use some idea like group control via party/raid/whisper (/count group members,,target/) or chatfilters usage .
https://github.com/Lidocian/Ikebotui

i'm really appreciated with your work!

pls answer

**Comment by ike3** [comment]
Hi!

I'd recommend try to use SQL strategies instead of C++. They are a bit easier to implement and do not require any compilation and server restart. They lack cppunit tests though.

Take a look to characters_ai_playerbot_custom_strategy.sql script. Basically this a bunch of lines such as

    (NULL, 'say', 'critical health>emote::helpme|99,say::critical health|98'),

here `critical health` is the trigger and `emote::helpme` is the action, `99` is the priority and `say` is the strategy name

So, for example 

        triggers.push_back(new TriggerNode(
            "seal",
            NextAction::array(0, new NextAction("seal of wisdom", 90.0f), NULL)));

can be replaced with one line such as 'seal>seal of wisdom|90' (inserted into the table)

When the data in the DB, `co +custom::<your_strategy_name>` and it will be loaded
If something went wrong, change the DB data, remove and add the strategy again.

P.S. There is an addon already https://github.com/ike3/mangosbot-addon check it out)

**Comment by Lidocian** [comment]
Thank you! I will try it

**Comment by Lidocian** [comment]
Awesome!!!!

 i need to add seal of the crusader in c++ and when  im done i can use sql  :)

**Comment by Lidocian** [comment]
If you want i can post all default rotations (dps) 1.12 -> 3.3.5 for each class
